# Nota:
# MPFS2.jar has been found here: https://wunderweatherstation.wordpress.com/help/web-upload/
#
.PHONY: out/test.bin

out/test.bin: 
	java -jar MPFS2.jar /xgzip '*.txt' /mpfs2 files . out/test.bin